BEGIN -- 声明异常处理变量
DECLARE SQLCODE INTEGER DEFAULT 0;
DECLARE SQLSTATE CHAR(5) DEFAULT ’ 00000 ’;
DECLARE V_PROCEDURE_NAME VARCHAR(25) DEFAULT 'SJCK.SOME_PROCEDURE_NAME';
DECLARE V_MSG VARCHAR(512);
DECLARE V_RET INTEGER;
-- 声明存储过程使用变量
DECLARE SQL VARCHAR(10000);
DECLARE STEP INTEGER DEFAULT 0;
DECLARE DATE_CURRENT VARCHAR(10);
-- 当前日期，格式为YYYYMMDD
-- 设置变量值
SET
  DATE_CURRENT = TO_CHAR(CURRENT DATE, 'YYYYMMDD');
-- 抛异常
DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
VALUES
(
    '存储过错' || V_PROCEDURE_NAME || '调用失败，在步骤' || CHAR(STEP) || '结束。' || 'SQLCode: ' || RTRIM(CHAR(SQLCODE)) || '; SQLState: ' || CHAR(SQLSTATE)
  ) INTO V_MSG;
SET
  V_RET = -1;
END;
-- 1 BALABALA
SET
  SQL = 'SOME SQL STATEMENT';
EXECUTE IMMEDIATE SQL;
COMMIT;
SET
  STEP = 1;
-- 2 BALABALA
-- 结束设置
SET
  V_RET = 0;
SET
  V_MSG = V_PROCEDURE_NAME || ' Finished!';
END